*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADUVSWITCH_USER................................*
FORM GET_DATA_ZADUVSWITCH_USER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADU_SWITCH_USER WHERE
(VIM_WHERETAB) .
    CLEAR ZADUVSWITCH_USER .
ZADUVSWITCH_USER-CLIENT =
ZADU_SWITCH_USER-CLIENT .
ZADUVSWITCH_USER-CODE =
ZADU_SWITCH_USER-CODE .
ZADUVSWITCH_USER-USERNAME =
ZADU_SWITCH_USER-USERNAME .
    SELECT SINGLE * FROM ZADU_SWITCH WHERE
CODE = ZADU_SWITCH_USER-CODE .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZADUVSWITCH_USER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADUVSWITCH_USER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADUVSWITCH_USER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADUVSWITCH_USER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADU_SWITCH_USER WHERE
  CODE = ZADUVSWITCH_USER-CODE AND
  USERNAME = ZADUVSWITCH_USER-USERNAME .
    IF SY-SUBRC = 0.
    DELETE ZADU_SWITCH_USER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADU_SWITCH_USER WHERE
  CODE = ZADUVSWITCH_USER-CODE AND
  USERNAME = ZADUVSWITCH_USER-USERNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADU_SWITCH_USER.
    ENDIF.
ZADU_SWITCH_USER-CLIENT =
ZADUVSWITCH_USER-CLIENT .
ZADU_SWITCH_USER-CODE =
ZADUVSWITCH_USER-CODE .
ZADU_SWITCH_USER-USERNAME =
ZADUVSWITCH_USER-USERNAME .
    IF SY-SUBRC = 0.
    UPDATE ZADU_SWITCH_USER ##WARN_OK.
    ELSE.
    INSERT ZADU_SWITCH_USER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADUVSWITCH_USER-UPD_FLAG,
STATUS_ZADUVSWITCH_USER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADUVSWITCH_USER.
  SELECT SINGLE * FROM ZADU_SWITCH_USER WHERE
CODE = ZADUVSWITCH_USER-CODE AND
USERNAME = ZADUVSWITCH_USER-USERNAME .
ZADUVSWITCH_USER-CLIENT =
ZADU_SWITCH_USER-CLIENT .
ZADUVSWITCH_USER-CODE =
ZADU_SWITCH_USER-CODE .
ZADUVSWITCH_USER-USERNAME =
ZADU_SWITCH_USER-USERNAME .
    SELECT SINGLE * FROM ZADU_SWITCH WHERE
CODE = ZADU_SWITCH_USER-CODE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADUVSWITCH_USER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADUVSWITCH_USER-CODE TO
ZADU_SWITCH_USER-CODE .
MOVE ZADUVSWITCH_USER-USERNAME TO
ZADU_SWITCH_USER-USERNAME .
MOVE ZADUVSWITCH_USER-CLIENT TO
ZADU_SWITCH_USER-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADU_SWITCH_USER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADU_SWITCH_USER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADU_SWITCH_USER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZADUVSWITCH_USER USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZADU_SWITCH_USER-CLIENT =
ZADUVSWITCH_USER-CLIENT .
ZADU_SWITCH_USER-CODE =
ZADUVSWITCH_USER-CODE .
ZADU_SWITCH_USER-USERNAME =
ZADUVSWITCH_USER-USERNAME .
    SELECT SINGLE * FROM ZADU_SWITCH WHERE
CODE = ZADU_SWITCH_USER-CODE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
