*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADUVSWITCH.....................................*
FORM GET_DATA_ZADUVSWITCH.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADU_SWITCH WHERE
(VIM_WHERETAB) .
    CLEAR ZADUVSWITCH .
ZADUVSWITCH-CLIENT =
ZADU_SWITCH-CLIENT .
ZADUVSWITCH-CODE =
ZADU_SWITCH-CODE .
ZADUVSWITCH-STATUS =
ZADU_SWITCH-STATUS .
ZADUVSWITCH-NAME =
ZADU_SWITCH-NAME .
ZADUVSWITCH-CUSTOM_CHECK =
ZADU_SWITCH-CUSTOM_CHECK .
<VIM_TOTAL_STRUC> = ZADUVSWITCH.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADUVSWITCH .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADUVSWITCH.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADUVSWITCH-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADU_SWITCH WHERE
  CODE = ZADUVSWITCH-CODE .
    IF SY-SUBRC = 0.
    DELETE ZADU_SWITCH .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADU_SWITCH WHERE
  CODE = ZADUVSWITCH-CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADU_SWITCH.
    ENDIF.
ZADU_SWITCH-CLIENT =
ZADUVSWITCH-CLIENT .
ZADU_SWITCH-CODE =
ZADUVSWITCH-CODE .
ZADU_SWITCH-STATUS =
ZADUVSWITCH-STATUS .
ZADU_SWITCH-NAME =
ZADUVSWITCH-NAME .
ZADU_SWITCH-CUSTOM_CHECK =
ZADUVSWITCH-CUSTOM_CHECK .
    IF SY-SUBRC = 0.
    UPDATE ZADU_SWITCH ##WARN_OK.
    ELSE.
    INSERT ZADU_SWITCH .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADUVSWITCH-UPD_FLAG,
STATUS_ZADUVSWITCH-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADUVSWITCH.
  SELECT SINGLE * FROM ZADU_SWITCH WHERE
CODE = ZADUVSWITCH-CODE .
ZADUVSWITCH-CLIENT =
ZADU_SWITCH-CLIENT .
ZADUVSWITCH-CODE =
ZADU_SWITCH-CODE .
ZADUVSWITCH-STATUS =
ZADU_SWITCH-STATUS .
ZADUVSWITCH-NAME =
ZADU_SWITCH-NAME .
ZADUVSWITCH-CUSTOM_CHECK =
ZADU_SWITCH-CUSTOM_CHECK .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADUVSWITCH USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADUVSWITCH-CODE TO
ZADU_SWITCH-CODE .
MOVE ZADUVSWITCH-CLIENT TO
ZADU_SWITCH-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADU_SWITCH'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADU_SWITCH TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADU_SWITCH'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
